import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { TodoProvider } from './context/TodoContext';
import { ThemeProvider } from '@mui/material';
import theme from './components/theme/theme';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='ja'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <TodoProvider>
                    <AppRouterCacheProvider>
                        <ThemeProvider theme={theme}>{children}</ThemeProvider>
                    </AppRouterCacheProvider>
                </TodoProvider>
            </body>
        </html>
    );
}
